name: Label PRs
permissions:
  pull-requests: write
on:
  pull_request:
    types: [opened, reopened, converted_to_draft, ready_for_review]
  pull_request_review:
    types: [submitted]
jobs:
  opened:
    if: (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review') && github.event.pull_request.state == 'open' && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["needs-review", "needs-qa"]
            })
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["in-progress"]
              })
            } catch(err) {
              if (!(err.name === "HttpError" && err.status === 404)) {
                throw new err
              }
            }
  draft:
    if: (github.event.action == 'opened' || github.event.action == 'converted_to_draft') && github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["in-progress"]
            })
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["needs-review"]
              })
            } catch(err) {
              if (!(err.name === "HttpError" && err.status === 404)) {
                throw new err
              }
            }
  approved:
    if: github.event.action == 'submitted' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
           try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["needs-review"]
              })
            } catch(err) {
              if (!(err.name === "HttpError" && err.status === 404)) {
                throw new err
              }
            }
